### ISSUE TITLE
correction factor

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#22]
in computeDS 

 correction_factor = 1 / (2 * combined['R'] * (1 + combined['m']))
    shear = combined['d_sigma'] * correction_factor

correction factor => calibration factor

and let's not call the result shear.

We should simply call the result => delta_sigma

**Comment by dr-guangtou** [comment]
Will address this when I work on `computeDS.py`. 
    - `combined['m']` should be `combined['k']`
    - Will change other naming too

**Comment by dr-guangtou** [comment]
Although `runComputeDS.py` needs a lot of rewrite, change the style now:

* `correction_factor` to `calibration_factor`
* `shear` to `delta_sigma` 
* change the function name `calculate_net_shear` to `calculate_delta_sigma_gR` (gR stands for galaxy-random; as in Singh et al. 2017)
* change the function name `jackknife_errors` to `calculate_jackknife_errors`. (since there is a variable named `jackknife_errors` too). 

Close the issue
